# Generated by Django 5.2.11 on 2026-09-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=50)),
                ('mensagem', models.TextField(blank=True)),
                ('curriculo', models.FileField(upload_to='curriculos/%Y/%m/', verbose_name='currículo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='recebida em')),
            ],
            options={
                'verbose_name': 'candidatura (Trabalhe Conosco)',
                'verbose_name_plural': 'candidaturas (Trabalhe Conosco)',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='recebida em')),
            ],
            options={
                'verbose_name': 'mensagem de contato',
                'verbose_name_plural': 'mensagens de contato',
                'ordering': ['-criado_em'],
            },
        ),
    ]
