# Generated by Django 5.2.11 on 2026-09-24 12:55

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatoIntegridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(default=website.models._novo_protocolo, editable=False, max_length=12, unique=True)),
                ('categoria', models.CharField(choices=[('etica', 'Violação do Código de Conduta e Ética'), ('fraude', 'Fraude ou desvio de recursos'), ('corrupcao', 'Corrupção ou suborno'), ('conflito', 'Conflito de interesses'), ('assedio', 'Assédio ou discriminação'), ('seguranca', 'Segurança, saúde ou meio ambiente'), ('lgpd', 'Privacidade e proteção de dados (LGPD)'), ('outros', 'Outros')], max_length=20)),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('quando_onde', models.CharField(blank=True, max_length=255, verbose_name='quando e onde ocorreu')),
                ('envolvidos', models.CharField(blank=True, max_length=255, verbose_name='pessoas ou áreas envolvidas')),
                ('nome', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_analise', 'Em análise'), ('concluido', 'Concluído')], default='novo', max_length=20)),
                ('anotacoes', models.TextField(blank=True, verbose_name='anotações internas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
            ],
            options={
                'verbose_name': 'relato do Canal de Integridade',
                'verbose_name_plural': 'relatos do Canal de Integridade',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='candidatura',
            name='aceite_privacidade',
            field=models.BooleanField(default=False, verbose_name='aceitou a política de privacidade'),
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='aceite_privacidade',
            field=models.BooleanField(default=False, verbose_name='aceitou a política de privacidade'),
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='assunto',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('operacoes', 'Operações'), ('administrativo', 'Administrativo / Financeiro'), ('outros', 'Outros assuntos')], default='comercial', max_length=20),
        ),
        migrations.AddField(
            model_name='mensagemcontato',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='telefone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mensagemcontato',
            name='mensagem',
            field=models.TextField(),
        ),
    ]
